name: masamune_flutter
description: >-
  Module that provides the flutter support function of the Masamune framework.
  State management by PathMap, page management, etc.
version: 0.4.9+9
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune_flutter

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # GUI
  intl: ^0.16.1
  photo_view: ^0.9.2
  solid_bottom_sheet: ^0.1.9
  loading_animations: ^2.1.0  
  flappy_search_bar: ^1.7.2
  video_player: ^0.10.11+2
  # Animation  
  flutter_sequence_animation: ^3.0.0  
  datetime_picker_formfield: ^1.0.0
  cached_network_image: ^2.3.1
  # Masamune
  masamune_core: ^0.4.0
  masamune_localize: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Masamune
  masamune_test: ^0.1.0

# dependency_overrides:
#   masamune_core:
#     path: ../masamune_core/
#   masamune_localize:
#     path: ../masamune_localize/
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
